### ISSUE TITLE
能加一个同时获取ipv6的么？

### ISSUE THREAD

**Issue by EndBoy520** [cnwikee/CheckTMDB#1]
这个也能获取ipv6
https://dnschecker.org/#AAAA/api.themoviedb.org

**Comment by cnwikee** [comment]
有现成的，我自己就是IPv6，没同步到github，回头我同步上去。

________________________________
发件人: EndBoy520 ***@***.***>
发送时间: 2024年12月16日 19:25
收件人: cnwikee/CheckTMDB ***@***.***>
抄送: Subscribed ***@***.***>
主题: [cnwikee/CheckTMDB] 能加一个同时获取ipv6的么？ (Issue #1)


这个也能获取ipv6
https://dnschecker.org/#AAAA/api.themoviedb.org

―

**Comment by EndBoy520** [comment]
这个你是放action里面用的？怎么不把输出结果直接写入系统hosts里呐。这该咋写呐，我之前找了一个只有ipv4，那个可以写入和更新hosts，就是没有ipv6，获取的也不全。把https://github.com/ChenXinBest/hosts_check/blob/master/DnsParse.py这个的hosts的写入更新功能，添加到这个代码里面该怎么改呐

**Comment by cnwikee** [comment]
> 这个你是放action里面用的？怎么不把输出结果直接写入系统hosts里呐。这该咋写呐，我之前找了一个只有ipv4，那个可以写入和更新hosts，就是没有ipv6，获取的也不全。把https://github.com/ChenXinBest/hosts_check/blob/master/DnsParse.py 这个的hosts的写入更新功能，添加到这个代码里面该怎么改呐

win系统自己写个bat，抓取你需要的IPv4或IPv6数据，写入本机hosts就行了。
